---
- name: Add Tor repository [ 1 / 2 ]
  become: true
  become_method: sudo
  apt_repository:
    repo: deb http://deb.torproject.org/torproject.org {{ distribution }} main
    state: present
    update_cache: false

- name: Add Tor repository [ 2 / 2 ]
  become: true
  become_method: sudo
  apt_repository:
    repo: deb-src http://deb.torproject.org/torproject.org {{ distribution }} main
    state: present
    update_cache: false

- name: Add gpg key used to sign packages [ 1 / 2 ]
  become: true
  become_method: sudo
  shell: "curl https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc | gpg --import"

- name: Add gpg key used to sign packages [ 2 / 2 ]
  become: true
  become_method: sudo
  shell: "gpg --export A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89 | apt-key add -"

- name: Update repos
  become: true
  become_method: sudo
  apt:
     update_cache: yes

- name: Install tor package
  become: true
  become_method: sudo
  apt:
    pkg: "tor"
    state: latest
    update_cache: true

- name: Backup torrc file
  become: true
  become_method: sudo
  command: mv /etc/tor/torrc /etc/tor/torrc.original

- name: Copy local torrc to /etc/tor
  become: true
  become_method: sudo
  copy:
    src: "{{ item }}"
    dest: "/etc/tor"
    owner: "{{ cuckoo_user }}"
    group: "{{ cuckoo_user }}"
    mode: 0644
  with_fileglob:
    - ../files/torrc

- name: Enable and restart Tor service
  become: true
  become_method: sudo
  service:
    name: tor
    state: restarted
    enabled: true
