---
# This is derived from
# https://medium.com/@xNymia/malware-analysis-first-steps-creating-your-lab-21b769fb2a64
# ...

- name: Add InetSim repository
  become: true
  become_method: sudo
  shell: echo "deb http://www.inetsim.org/debian/ binary/" > /etc/apt/sources.list.d/inetsim.list

- name: Add InetSim signing key
  become: true
  become_method: sudo
  shell: wget -O - http://www.inetsim.org/inetsim-archive-signing-key.asc | apt-key add -

- name: Install InetSim
  become: true
  become_method: sudo
  apt:
    name: inetsim
    state: latest
    update_cache: true

- name: Backup inetsim.conf file
  become: true
  become_method: sudo
  command: cp /etc/inetsim/inetsim.conf /etc/inetsim/inetsim.conf.original

- name: Copy local inetsim.conf to /etc/inetsim
  become: true
  become_method: sudo
  copy:
    src: "{{ item }}"
    dest: "/etc/inetsim"
    owner: "root"
    group: "root"
    mode: 0644
  with_fileglob:
    - ../files/inetsim.conf

- name: Backup inetsim file
  become: true
  become_method: sudo
  command: cp /etc/default/inetsim /etc/default/inetsim.original

- name: Copy local inetsim to /etc/default
  become: true
  become_method: sudo
  copy:
    src: "{{ item }}"
    dest: "/etc/default"
    owner: "root"
    group: "root"
    mode: 0644
  with_fileglob:
    - ../files/inetsim

- name: Starting and enabling InetSim
  become: true
  become_method: sudo
  systemd:
    state: started
    name: suricata.service
